# Generated by Django 3.2.9 on 2021-11-26 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Franck', max_length=50, verbose_name='Nom')),
                ('dob', models.DateField(default=datetime.date(1984, 11, 26), verbose_name='DOB')),
            ],
        ),
    ]
